In [2]:
import numpy as np

data_1d = np.arange(10, 30)
data_2d = data_1d.reshape(4, 5)

print("Original Array:")
print(data_2d)
print("\nShape:", data_2d.shape)
print("Size:", data_2d.size)
print("Dimensions:", data_2d.ndim)

data_2d = data_2d.astype(np.float64)

print("\nData Type After Casting:", data_2d.dtype)

Original Array:
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

Shape: (4, 5)
Size: 20
Dimensions: 2

Data Type After Casting: float64


In [4]:
import numpy as np

np.random.seed(42)

A = np.random.randint(1, 101, size=(10, 10))

print("--- Initial 10x10 Array A ---")
print(A)

B = A[3:7, 2:8]

print("\n--- Extracted Sub-array B (Shape: {}) ---".format(B.shape))
print(B)

mask = (A > 50) & (A < 75)

elements_replaced = np.sum(mask)

A[mask] = -1

print("\n--- Array A After Conditional Assignment ---")
print(A)

print("\n--- Final Results ---")
print("Shape of extracted sub-array B:", B.shape)
print("Number of elements replaced in A:", elements_replaced)

--- Initial 10x10 Array A ---
[[ 52  93  15  72  61  21  83  87  75  75]
 [ 88 100  24   3  22  53   2  88  30  38]
 [  2  64  60  21  33  76  58  22  89  49]
 [ 91  59  42  92  60  80  15  62  62  47]
 [ 62  51  55  64   3  51   7  21  73  39]
 [ 18   4  89  60  14   9  90  53   2  84]
 [ 92  60  71  44   8  47  35  78  81  36]
 [ 50   4   2   6  54   4  54  93  63  18]
 [ 90  44  34  74  62 100  14  95  48  15]
 [ 72  78  87  62  40  85  80  82  53  24]]

--- Extracted Sub-array B (Shape: (4, 6)) ---
[[42 92 60 80 15 62]
 [55 64  3 51  7 21]
 [89 60 14  9 90 53]
 [71 44  8 47 35 78]]

--- Array A After Conditional Assignment ---
[[ -1  93  15  -1  -1  21  83  87  75  75]
 [ 88 100  24   3  22  -1   2  88  30  38]
 [  2  -1  -1  21  33  76  -1  22  89  49]
 [ 91  -1  42  92  -1  80  15  -1  -1  47]
 [ -1  -1  -1  -1   3  -1   7  21  -1  39]
 [ 18   4  89  -1  14   9  90  -1   2  84]
 [ 92  -1  -1  44   8  47  35  78  81  36]
 [ 50   4   2   6  -1   4  -1  93  -1  18]
 [ 90  44  34  -1

In [5]:
import numpy as np

A = np.ones((1, 5), dtype=np.int32)
B = np.zeros((5, 1), dtype=np.int32)

print("--- Initial Arrays ---")
print("Array A (1x5):\n", A)
print("Array B (5x1):\n", B)

A_t = A.T

print("\nArray A_t (A Transposed, 5x1):\n", A_t)

C = np.hstack((A_t, B))

print("\n--- Result C (Vertical Stack: A_t and B -> 5x2) ---")
print("Array C:\n", C)
print("Shape of C:", C.shape)

A_repeated = np.tile(A, 2)
D = np.hstack((A, A_repeated))

print("\n--- Result D (Horizontal Stack: A and A Repeated -> 1x15) ---")
print("Array D:\n", D)
print("Shape of D:", D.shape)

--- Initial Arrays ---
Array A (1x5):
 [[1 1 1 1 1]]
Array B (5x1):
 [[0]
 [0]
 [0]
 [0]
 [0]]

Array A_t (A Transposed, 5x1):
 [[1]
 [1]
 [1]
 [1]
 [1]]

--- Result C (Vertical Stack: A_t and B -> 5x2) ---
Array C:
 [[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]
Shape of C: (5, 2)

--- Result D (Horizontal Stack: A and A Repeated -> 1x15) ---
Array D:
 [[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
Shape of D: (1, 15)


In [6]:
import numpy as np

np.random.seed(42)

M = np.random.randint(10, 51, size=(5, 5))

print("--- 1. Original 5x5 Array M ---")
print(M)

M_log = np.log(M)

print("\n--- 2. Vectorized Operation (Natural Logarithm M_log) ---")
print("First row of M_log:")
print(M_log[0]) 

col_sums = np.sum(M, axis=0)

print("\n--- 3. Column Sums (Aggregated along Axis 0) ---")
print("Resulting Array (col_sums):\n", col_sums)
print("Shape of col_sums:", col_sums.shape)

row_means = np.mean(M, axis=1)

print("\n--- 4. Row Means (Aggregated along Axis 1) ---")
print("Resulting Array (row_means):\n", row_means)
print("Shape of row_means:", row_means.shape)

--- 1. Original 5x5 Array M ---
[[48 38 24 17 30]
 [48 28 32 20 20]
 [33 45 49 33 12]
 [31 11 33 39 47]
 [11 30 42 21 31]]

--- 2. Vectorized Operation (Natural Logarithm M_log) ---
First row of M_log:
[3.87120101 3.63758616 3.17805383 2.83321334 3.40119738]

--- 3. Column Sums (Aggregated along Axis 0) ---
Resulting Array (col_sums):
 [171 152 180 130 140]
Shape of col_sums: (5,)

--- 4. Row Means (Aggregated along Axis 1) ---
Resulting Array (row_means):
 [31.4 29.6 34.4 32.2 27. ]
Shape of row_means: (5,)


In [7]:
import numpy as np

np.random.seed(42)

M = np.random.randint(10, 21, size=(5, 3))
V = np.array([[1, 2, 3]])

print("--- 1. Initial Arrays ---")
print("Matrix M (5x3):\n", M)
print("Vector V (1x3):\n", V)

M_added = M + V

print("\n--- 2. Broadcasting Addition (M + V) ---")
print("Result M_added (First Row):\n", M_added[0])
print("Shape of M_added:", M_added.shape)
print("Verification: 13 + 1 = 14, 19 + 2 = 21, 15 + 3 = 18")

W_flat = np.array([10, 20, 30, 40, 50])
W = W_flat.reshape(5, 1) 

M_multiplied = M * W

print("\n--- 3. Broadcasting Multiplication (M * W) ---")
print("Vector W (5x1):\n", W)
print("\nResult M_multiplied (First Column):")
print(M_multiplied[:, 0]) 
print("Shape of M_multiplied:", M_multiplied.shape)
print("Verification: 13 * 10 = 130, 15 * 20 = 300, 11 * 30 = 330...")

--- 1. Initial Arrays ---
Matrix M (5x3):
 [[16 13 20]
 [17 14 16]
 [19 12 16]
 [20 20 17]
 [14 13 17]]
Vector V (1x3):
 [[1 2 3]]

--- 2. Broadcasting Addition (M + V) ---
Result M_added (First Row):
 [17 15 23]
Shape of M_added: (5, 3)
Verification: 13 + 1 = 14, 19 + 2 = 21, 15 + 3 = 18

--- 3. Broadcasting Multiplication (M * W) ---
Vector W (5x1):
 [[10]
 [20]
 [30]
 [40]
 [50]]

Result M_multiplied (First Column):
[160 340 570 800 700]
Shape of M_multiplied: (5, 3)
Verification: 13 * 10 = 130, 15 * 20 = 300, 11 * 30 = 330...
