In [1]:
import numpy as np

# 1. Creation: Create a 1D array from 10 to 29 (inclusive)
data_1d = np.arange(10, 30)

# 2. Reshaping: Transform to a 2D array of 4x5
data_2d = data_1d.reshape(4, 5)

# 3. Inspection & Output
print("Original Array:")
print(data_2d)
print("\nShape:", data_2d.shape)
print("Size:", data_2d.size)
print("Dimensions:", data_2d.ndim)

# 4. Type Casting: Change data type to float64
data_2d = data_2d.astype(np.float64)

print("\nData Type After Casting:", data_2d.dtype)

Original Array:
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

Shape: (4, 5)
Size: 20
Dimensions: 2

Data Type After Casting: float64


In [2]:
import numpy as np

# Set a random seed for reproducible results (optional, but recommended for testing)
np.random.seed(42)

# 1. Creation: Create a 10x10 array named 'A' with random integers between 1 and 100
A = np.random.randint(1, 101, size=(10, 10))

print("--- Initial 10x10 Array A ---")
print(A)

# 2. Basic Slicing: Extract sub-array B
# Rows: 3 through 6 (3:7)
# Columns: 2 through 7 (2:8)
B = A[3:7, 2:8]

print("\n--- Extracted Sub-array B (Shape: {}) ---".format(B.shape))
print(B)

# 3. & 4. Boolean Masking and Conditional Assignment
# Condition: Numbers > 50 AND < 75
# The & operator is used for element-wise logical AND in NumPy
mask = (A > 50) & (A < 75)

# Count how many elements satisfy the mask before assignment
elements_replaced = np.sum(mask)

# Replace all elements that satisfy the mask with -1
A[mask] = -1

print("\n--- Array A After Conditional Assignment ---")
print(A)

# Final required output
print("\n--- Final Results ---")
print(f"Shape of extracted sub-array B: {B.shape}")
print(f"Number of elements replaced in A: {elements_replaced}")

--- Initial 10x10 Array A ---
[[ 52  93  15  72  61  21  83  87  75  75]
 [ 88 100  24   3  22  53   2  88  30  38]
 [  2  64  60  21  33  76  58  22  89  49]
 [ 91  59  42  92  60  80  15  62  62  47]
 [ 62  51  55  64   3  51   7  21  73  39]
 [ 18   4  89  60  14   9  90  53   2  84]
 [ 92  60  71  44   8  47  35  78  81  36]
 [ 50   4   2   6  54   4  54  93  63  18]
 [ 90  44  34  74  62 100  14  95  48  15]
 [ 72  78  87  62  40  85  80  82  53  24]]

--- Extracted Sub-array B (Shape: (4, 6)) ---
[[42 92 60 80 15 62]
 [55 64  3 51  7 21]
 [89 60 14  9 90 53]
 [71 44  8 47 35 78]]

--- Array A After Conditional Assignment ---
[[ -1  93  15  -1  -1  21  83  87  75  75]
 [ 88 100  24   3  22  -1   2  88  30  38]
 [  2  -1  -1  21  33  76  -1  22  89  49]
 [ 91  -1  42  92  -1  80  15  -1  -1  47]
 [ -1  -1  -1  -1   3  -1   7  21  -1  39]
 [ 18   4  89  -1  14   9  90  -1   2  84]
 [ 92  -1  -1  44   8  47  35  78  81  36]
 [ 50   4   2   6  -1   4  -1  93  -1  18]
 [ 90  44  34  -1

In [3]:
import numpy as np

# 1. Creation: Create arrays A and B
# A: 1x5 array of ones (integer dtype)
A = np.ones((1, 5), dtype=np.int32)
# B: 5x1 array of zeros (integer dtype)
B = np.zeros((5, 1), dtype=np.int32)

print("--- Initial Arrays ---")
print(f"Array A (1x5):\n{A}")
print(f"Array B (5x1):\n{B}")

# 2. Transpose: Create A_t
# Transposing a 1x5 array results in a 5x1 array
A_t = A.T

print(f"\nArray A_t (A Transposed, 5x1):\n{A_t}")

# 3. Vertical Stack: Combine A_t and B (both 5x1)
# Resulting array C will be 5x2
C = np.hstack((A_t, B))

# NOTE: We used hstack because A_t and B both have 5 rows and need to be joined column-wise.
# If we had used vstack, it would result in a 10x1 array.
# For a 5x2 result from two 5x1 arrays, horizontal stacking is required.

print("\n--- Result C (Vertical Stack: A_t and B -> 5x2) ---")
print(f"Array C:\n{C}")
print(f"Shape of C: {C.shape}")

# 4. Horizontal Stack: Combine A and A repeated twice (1x5 + 1x10)
# A: 1x5, np.tile(A, 2): 1x10. The resulting array D will be 1x15.
A_repeated = np.tile(A, 2)
D = np.hstack((A, A_repeated))

print("\n--- Result D (Horizontal Stack: A and A Repeated -> 1x15) ---")
print(f"Array D:\n{D}")
print(f"Shape of D: {D.shape}")

--- Initial Arrays ---
Array A (1x5):
[[1 1 1 1 1]]
Array B (5x1):
[[0]
 [0]
 [0]
 [0]
 [0]]

Array A_t (A Transposed, 5x1):
[[1]
 [1]
 [1]
 [1]
 [1]]

--- Result C (Vertical Stack: A_t and B -> 5x2) ---
Array C:
[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]
Shape of C: (5, 2)

--- Result D (Horizontal Stack: A and A Repeated -> 1x15) ---
Array D:
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
Shape of D: (1, 15)


In [4]:
import numpy as np

# Set a random seed for reproducible results (optional)
np.random.seed(42)

# 1. Creation: Create a 5x5 array 'M' with random positive integers between 10 and 50
M = np.random.randint(10, 51, size=(5, 5))

print("--- 1. Original 5x5 Array M ---")
print(M)

# 2. Vectorized Operation: Calculate the natural logarithm (ln)
# np.log() is a Universal Function (ufunc) that applies element-wise
M_log = np.log(M)

print("\n--- 2. Vectorized Operation (Natural Logarithm M_log) ---")
print("First row of M_log:")
print(M_log[0]) # Print just the first row for brevity

# 3. Column-wise Aggregation (Axis 0): Sum of Columns
# axis=0 collapses the rows, resulting in one sum per column (5 elements)
col_sums = np.sum(M, axis=0)

print("\n--- 3. Column Sums (Aggregated along Axis 0) ---")
print(f"Resulting Array (col_sums):\n{col_sums}")
print(f"Shape of col_sums: {col_sums.shape}")

# 4. Row-wise Aggregation (Axis 1): Mean of Rows
# axis=1 collapses the columns, resulting in one mean per row (5 elements)
row_means = np.mean(M, axis=1)

print("\n--- 4. Row Means (Aggregated along Axis 1) ---")
print(f"Resulting Array (row_means):\n{row_means}")
print(f"Shape of row_means: {row_means.shape}")

--- 1. Original 5x5 Array M ---
[[48 38 24 17 30]
 [48 28 32 20 20]
 [33 45 49 33 12]
 [31 11 33 39 47]
 [11 30 42 21 31]]

--- 2. Vectorized Operation (Natural Logarithm M_log) ---
First row of M_log:
[3.87120101 3.63758616 3.17805383 2.83321334 3.40119738]

--- 3. Column Sums (Aggregated along Axis 0) ---
Resulting Array (col_sums):
[171 152 180 130 140]
Shape of col_sums: (5,)

--- 4. Row Means (Aggregated along Axis 1) ---
Resulting Array (row_means):
[31.4 29.6 34.4 32.2 27. ]
Shape of row_means: (5,)
