In [10]:
import numpy as np

arr = np.array([10, 20, 30])
print(arr)

[10 20 30]


In [9]:
arr_gen = np.arange(5)
print(arr_gen)

[0 1 2 3 4]


In [8]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a.shape)

(2, 3)


In [7]:
arr_math = np.array([1, 2, 3])

result = arr_math * 10
print(result)

[10 20 30]


In [6]:
arr_idx = np.array([10, 20, 30, 40])

print(arr_idx[2])

30


In [31]:
arr = np.arange(6)
matrix = arr.reshape(2, 3)
print(matrix)

[[0 1 2]
 [3 4 5]]


In [20]:
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

print(matrix[1, 1])
print(matrix[:, 2])

5
[3 6]


In [21]:
matrix = np.array([[7, 8, 9], 
                   [10, 11, 12]])

print(matrix.sum(axis=0))

[17 19 21]


In [22]:
matrix = np.array([[7, 8, 9], 
                   [4, 5, 6]])

print(matrix.T)

[[7 4]
 [8 5]
 [9 6]]


In [29]:
arr = np.array([5, 10, 25, 35])

mask = arr > 25
print(mask) 

[False False False  True]


In [27]:
arr = np.array([1, 5, 10, 15])

filtered = arr[arr < 8]
print(filtered)

[1 5]


In [28]:
arr = np.arange(1, 11)

result = arr[(arr > 3) & (arr < 8)]
print(result)

[4 5 6 7]


In [30]:
arr = np.array([10, -5, 20, -3])

arr[arr < 0] = 0
print(arr)

[10  0 20  0]


In [33]:
arr = np.array([5, 10, 15, 10])

indices = np.where(arr == 10)
print(indices) # Output: (array([1, 3]),) -> Indices 1 and 3

(array([1, 3]),)


In [34]:
arr = np.array([10, 20, 30])

print(np.mean(arr))

20.0


In [35]:
arr = np.array([10, 50, 100])

print(np.median(arr))

50.0


In [36]:
arr = np.array([10, 50, 20, 5])

print(np.argmax(arr))
# Output: 1 (Because 50 is at index 1)

1


In [37]:
arr = np.array([5, 10, 15])

print(np.std(arr))

4.08248290463863


In [38]:
arr = np.array([1, 1, 2, 2, 3, 3])

print(np.unique(arr))

[1 2 3]


In [39]:
# 1. Creation: The raw scores
raw_scores = np.array([58, 92, 45, 88, 72, 30])

# 2. Broadcasting: Add 5 to every score (The Curve)
curved_scores = raw_scores + 5

# 3. Boolean Indexing: Keep only scores >= 60 (Filtering)
passing_scores = curved_scores[curved_scores >= 60]

# 4. Aggregation: Find the mean of the passing students
class_average = np.mean(passing_scores)

# Results
print("Curved Scores: ", curved_scores)
print("Passing Scores:", passing_scores)
print("Final Average: ", class_average)

Curved Scores:  [63 97 50 93 77 35]
Passing Scores: [63 97 93 77]
Final Average:  82.5


In [40]:
# Shape is (2, 2, 2) -> 2 layers, 2 rows, 2 columns
arr_3d = np.zeros((2, 2, 2))
print(arr_3d)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [45]:
arr = np.array([
    [[1, 2], [3, 4]],   # Layer 0
    [[5, 6], [7, 8]]    # Layer 1
])

# Layer 1 (2nd matrix), Row 1 (2nd row), Col 0 (1st item)
print(arr[1, 1, 0])

7


In [44]:
print(arr[0])

[[1 2]
 [3 4]]


In [46]:
flat_arr = np.arange(12)

block = flat_arr.reshape(2, 2, 3)
print(block)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [47]:
# Create 2 layers of 3x3 ones
arr = np.ones((2, 3, 3))

result = arr.sum(axis=0)
print(result)
# The result is now a 2D matrix (3x3) full of 2s.

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
