In [1]:
import numpy as np

# 1. Creation: Create a 1D array from 10 to 29 (inclusive)
data_1d = np.arange(10, 30)

# 2. Reshaping: Transform to a 2D array of 4x5
data_2d = data_1d.reshape(4, 5)

# 3. Inspection & Output
print("Original Array:")
print(data_2d)
print("\nShape:", data_2d.shape)
print("Size:", data_2d.size)
print("Dimensions:", data_2d.ndim)

# 4. Type Casting: Change data type to float64
data_2d = data_2d.astype(np.float64)

print("\nData Type After Casting:", data_2d.dtype)

Original Array:
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

Shape: (4, 5)
Size: 20
Dimensions: 2

Data Type After Casting: float64
